#ifndef KARCHIVE_VERSION_H
#define KARCHIVE_VERSION_H

#define KARCHIVE_VERSION_STRING "5.32.0"
#define KARCHIVE_VERSION_MAJOR 5
#define KARCHIVE_VERSION_MINOR 32
#define KARCHIVE_VERSION_PATCH 0
#define KARCHIVE_VERSION ((5<<16)|(32<<8)|(0))

#endif
