QT.KArchive.VERSION = 5.32.0
QT.KArchive.MAJOR_VERSION = 5
QT.KArchive.MINOR_VERSION = 32
QT.KArchive.PATCH_VERSION = 0
QT.KArchive.name = KF5Archive
QT.KArchive.defines = 
QT.KArchive.includes = C:/Program Files (x86)/KArchive/include/KF5/KArchive
QT.KArchive.private_includes =
QT.KArchive.libs = C:/Program Files (x86)/KArchive/lib
QT.KArchive.depends = core
